server:
  port: 8082
  error:
    include-stacktrace: always

logging:
  config: src/main/resources/log4j2-spring.xml

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/data/learnumldb
    #    url: jdbc:h2:mem:learnumldb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  #    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
